Repository Piro-Yard/Yard, pull requests merged in 2022-02, with the labels that each got.

#30 [FEAT] 음악 검색기능, 중복 체크 미허용, input enter redirect 오류 해결
  templates/feedSearch.html
  templates/form.html
  templates/musicSearch.html
  user/urls.py
  user/views.py
Labels: feature ✨, fix 🛠, BE, 혜림🐻‍❄️

#32 [FEAT] Login/email verification
  config/settings.py
  templates/account/email/base_message.txt
  templates/account/email/email_confirmation_message.txt
  templates/account/email/email_confirmation_subject.txt
  templates/account/email/password_reset_key_message.txt
  templates/account/email/password_reset_key_subject.txt
Labels: feature ✨, BE, 유저관리😊, 우선순위1, 석현 🤓

#35 Feed search page/feed filter
  collectstatic/css/myPage.css
  collectstatic/css/style.css
  static/css/myPage.css
  static/css/style.css
  templates/feedSearch.html
  templates/form.html
  templates/mypage.html
  templates/searchBase.html
  user/urls.py
  user/views.py
Labels: feature ✨, BE, 피드관리, 혜림🐻‍❄️

#37 Main page/hash tag list
  templates/feedSearch.html
  templates/mainPage.html
  user/views.py
Labels: feature ✨, fix 🛠, BE, 피드관리, 혜림🐻‍❄️

#47 [FEAT] 소셜로그인 최초가입 시, 정보입력창으로 이동
  config/settings.py
  templates/myInfoRegister.html
  templates/socialaccount/signup.html
  user/forms.py
  user/models.py
  user/urls.py
  user/views.py
Labels: feature ✨, BE, 유저관리😊, 우선순위1, 석현 🤓

#57 [createFeed/modalForm] 피드 등록시 모달 창 생성하기
  templates/feedSearch.html
  user/migrations/0001_initial.py
  user/urls.py
  user/views.py
Labels: feature ✨, fix 🛠, FE, BE, 피드관리, 혜림🐻‍❄️, 지연 😑

#59 [FIX] 내 글 모아보기 폼 안가져와지는 오류 해결
  user/views.py
Labels: fix 🛠, BE, 피드관리, 혜림🐻‍❄️

#61 [FEAT] 로그인 페이지 CSS
  static/css/account.css
  static/css/style.css
  static/img/Google.png
  static/img/Naver.png
  static/img/logoPurple.png
  static/js/account.js
  templates/account/base.html
  templates/account/login.html
  templates/account/logout.html
  templates/socialaccount/login.html
Labels: feature ✨, FE, 유저관리😊, 우선순위2, 석현 🤓

#62 [FEAT] 좋아요 기능 완성 / [MERGE] devlop to feedLike
  templates/certDetail.html
  templates/feedSearch.html
  templates/searchBase.html
  user/views.py
Labels: feature ✨, refactor 🌈, FE, BE, 피드관리, 가은 👩🏻

#72 [Fix] reset.css 연결 / favicon 오류 해결 / reset.css 업데이트
  static/css/reset.css
  static/css/style.css
  templates/base.html
  templates/searchBase.html
Labels: fix 🛠, refactor 🌈, FE, 가은 👩🏻

#70 [FEAT] 피드 내용에 url 있을 때 하이퍼링크 생성 기능 구현
  config/settings.py
  templates/feedSearch.html
  templates/updateFeed.html
  user/views.py
Labels: feature ✨, FE, 피드관리, 지연 😑

#74 Feed search/my liked feed
  templates/feedSearch.html
  user/urls.py
  user/views.py
Labels: feature ✨, BE, 피드관리, 혜림🐻‍❄️

#75 Feed search/register hash tag
  config/settings.py
  static/js/search.js
  templates/feedSearch.html
  templates/mainPage.html
  templates/updateFeed.html
  user/forms.py
  user/models.py
  user/views.py
Labels: feature ✨, BE, 피드관리, 혜림🐻‍❄️

#76 Mypage/update info
  collectstatic/css/certificate.css
  static/css/certificate.css
  static/css/feed.css
  static/css/style.css
  static/css/variables.css
  static/img/plus.png
  static/js/cert.js
  static/js/mainPage.js
  static/js/search.js
  static/js/updateInfo.js
  templates/certificationRegister.html
  templates/feedSearch.html
  templates/updateFeed.html
Labels: refactor 🌈, FE, 나린 🐯

#79 Accounts page/css
  collectstatic/css/style.css
  static/css/account.css
  static/css/style.css
  static/css/variables.css
  templates/account/base.html
  templates/account/email.html
  templates/account/email_confirm.html
  templates/account/login.html
  templates/account/logout.html
  templates/account/password_change.html
  templates/account/password_reset.html
  templates/account/password_reset_done.html
  templates/account/password_reset_from_key.html
  templates/account/password_reset_from_key_done.html
  templates/account/signup.html
  templates/account/snippets/already_logged_in.html
  templates/account/verification_sent.html
  templates/myInfoRegister.html
  templates/socialaccount/authentication_error.html
  templates/socialaccount/connections.html
  templates/socialaccount/login.html
  templates/socialaccount/signup.html
  user/forms.py
Labels: refactor 🌈, FE, 유저관리😊, 우선순위1, 석현 🤓

#80 [FEAT] yard 홈페이지 og 태그 추가
  templates/base.html
  templates/searchBase.html
Labels: feature ✨, FE, 지연 😑

#82 [REFACT] mainpage description margin 설정
  static/css/mainPage.css
  user/migrations/0001_initial.py
  user/migrations/0002_feed_inputtags.py
Labels: refactor 🌈, FE, 나린 🐯

#83 [REFACT] 인증서 디테일 페이지 CSS 적용
  collectstatic/css/account.css
  collectstatic/css/base.css
  collectstatic/css/certificate.css
  collectstatic/css/feed.css
  collectstatic/css/mainPage.css
  collectstatic/css/reset.css
  collectstatic/css/style.css
  collectstatic/css/variables.css
  collectstatic/img/Google.png
  collectstatic/img/Naver.png
  collectstatic/img/default.jpeg
  collectstatic/img/logo.png
  collectstatic/img/logoPurple.png
  collectstatic/img/plus.png
  collectstatic/img/search.png
  collectstatic/img/searchBtn.png
  collectstatic/js/account.js
  collectstatic/js/cert.js
  collectstatic/js/feedLike.js
  collectstatic/js/mainPage.js
  collectstatic/js/myPage.js
  collectstatic/js/search.js
  collectstatic/js/updateInfo.js
  static/css/certDetail.css
  static/css/certificate.css
  static/css/style.css
  templates/base.html
  templates/certDetail.html
  templates/mainPage.html
  templates/mypage.html
Labels: refactor 🌈, FE, 인증서관리, 가은 👩🏻

#84 Cert detail page/sns
  collectstatic/css/myPage.css
  static/css/feed.css
  static/img/icon-facebook.png
  static/img/icon-kakao.png
  static/img/icon-twitter.png
  static/js/SNS.js
  static/js/feedpage.js
  templates/certDetail.html
  templates/feedSearch.html
Labels: feature ✨, refactor 🌈, FE, 나린 🐯

#85 [REFACT]Main page/css refact
  collectstatic/css/account.css
  collectstatic/css/myPage.css
  collectstatic/css/style.css
  static/css/account.css
  static/css/base.css
  static/css/feed.css
  static/css/myPage.css
  static/css/style.css
  static/css/variables.css
  templates/account/base.html
  templates/account/login.html
  templates/account/signup.html
  templates/mainPage.html
  templates/myInfoRegister.html
  templates/myinfo.html
  templates/mypage.html
  templates/searchBase.html
  user/migrations/0002_alter_user_nickname.py
  user/models.py
Labels: refactor 🌈, FE, 우선순위1, 석현 🤓

#88 [REFACT] mypage 인증서 없을때 보여주는 예시카드 HTML/CSS 추가
  static/css/certDetail.css
  static/css/myPage.css
  static/img/exam_albumImg.jpg
  templates/certDetail.html
  templates/certificationRegister.html
  templates/mypage.html
  templates/searchBase.html
  user/migrations/0001_initial.py
  user/migrations/0002_alter_user_nickname.py
Labels: refactor 🌈, FE, 인증서관리, 가은 👩🏻

#91 Feedpage/feed form
  collectstatic/audio/ flip.mp3
  collectstatic/css/certDetail.css
  collectstatic/css/certificate.css
  collectstatic/css/myPage.css
  collectstatic/img/icon-facebook.png
  collectstatic/img/icon-kakao.png
  collectstatic/img/icon-twitter.png
  collectstatic/js/SNS.js
  collectstatic/js/cert.js
  collectstatic/js/feedpage.js
  static/css/certificate.css
  static/css/feed.css
  static/css/myPage.css
  static/css/variables.css
  static/img/arrow.png
  static/js/cert.js
  static/js/feedpage.js
  static/js/myPage.js
  static/js/search.js
  templates/certificationRegister.html
  templates/feedSearch.html
  templates/updateFeed.html
Labels: FE, 나린 🐯

#92 [REFACT] feed.css, myinfoUpdate css
  collectstatic/css/feed.css
  static/css/account.css
  static/css/base.css
  static/css/variables.css
  static/img/birthday-cake.png
  static/img/icon-edit.png
  templates/myinfo.html
  templates/searchBase.html
  templates/updateInfo.html
  user/forms.py
Labels: refactor 🌈, FE, 석현 🤓

#93 [Fix] 예시뮤직카드 보이지 않는 문제 해결
  config/settings.py
  static/css/certDetail.css
  static/css/myPage.css
  templates/mypage.html
  templates/searchBase.html
Labels: fix 🛠, FE, 인증서관리, 가은 👩🏻

#94 [REFACT] Feed Page CSS 정리
  static/css/feed.css
  static/img/purpleNote.png
  templates/feedSearch.html
Labels: refactor 🌈, FE, 석현 🤓

#95 [REFACT] 내정보, myinfoRegister, 피드 CSS
  static/css/account.css
  static/css/feed.css
  templates/myInfoRegister.html
  templates/updateInfo.html
  user/forms.py
Labels: refactor 🌈, FE, 석현 🤓

#97 [Merge] certDetail_REDesign into develop
  static/css/certDetail.css
  static/css/myPage.css
  templates/mypage.html
  templates/searchBase.html
Labels: refactor 🌈, FE, 인증서관리, 가은 👩🏻

#98 [FIX] 해시태그 버튼, 해시태그 검색
  templates/feedSearch.html
  templates/updateFeed.html
  user/views.py
Labels: fix 🛠, FE, BE, 피드관리, 석현 🤓, 지연 😑

#101 [Fix] 다른 사람의 뮤직카드 수정.삭제 못하게 수정
  config/settings.py
  templates/certDetail.html
Labels: fix 🛠, FE, 인증서관리, 가은 👩🏻

#102 Allpage/footer
  static/css/base.css
  static/css/style.css
  templates/base.html
  templates/searchBase.html
  user/views.py
Labels: feature ✨, FE
